---
prometheus_file_sd_hosts: []
prometheus_file_sd_target_name: ""
prometheus_file_sd_prometheus_directory: /etc/prometheus
prometheus_file_sd_directory: "{{ prometheus_file_sd_prometheus_directory }}/file_sd"
prometheus_file_sd_target_directory: "{{ prometheus_file_sd_directory }}/{{ prometheus_file_sd_target_name }}"
prometheus_file_sd_target_file: "{{ prometheus_file_sd_target_directory }}/{{ inventory_hostname }}.yml"
prometheus_file_sd_target_port: ""
prometheus_file_sd_labels: {}
