---
- name: Ensure prometheus exporter systemd service
  ansible.builtin.include_role:
    name: damex.systemd.systemd_service
  vars:
    systemd_service_name: "{{ prometheus_exporter_service_name }}"
    systemd_service_restart_on: "{{ prometheus_exporter_default_configuration_file_state.changed }}"
