---
namespace: damex
name: prometheus
version: 1.2.0
readme: README.md
authors:
  - Roman Kuzmitskii <ansible@damex.org>
description: prometheus collection
license_file: LICENSE
tags:
  - linux
  - prometheus
repository: https://github.com/damex/ansible-collections-prometheus
dependencies:
  damex.apt: "*"
  damex.systemd: "*"
