---
- name: ensure file sd directory
  file:
    path: "{{ prometheus_file_sd_target_dir }}"
    state: "directory"
  loop: "{{ prometheus_file_sd_hosts }}"
  delegate_to: "{{ item }}"
  become: true

- name: ensure file sd target configuration
  template:
    src: "file_sd.yml.j2"
    dest: "{{ prometheus_file_sd_target_file }}"
  loop: "{{ prometheus_file_sd_hosts }}"
  delegate_to: "{{ item }}"
  become: true
