---
- name: Ensure file sd directory
  ansible.builtin.file:
    path: "{{ prometheus_file_sd_directory }}"
    state: directory
    mode: "0755"
  loop: "{{ prometheus_file_sd_hosts }}"
  delegate_to: "{{ item }}"
  become: true

- name: Ensure file sd target directory
  ansible.builtin.file:
    path: "{{ prometheus_file_sd_target_directory }}"
    state: directory
    mode: "0755"
  loop: "{{ prometheus_file_sd_hosts }}"
  delegate_to: "{{ item }}"
  become: true

- name: Ensure file sd target configuration
  ansible.builtin.template:
    src: file_sd.yml.j2
    dest: "{{ prometheus_file_sd_target_file }}"
    mode: "0644"
  loop: "{{ prometheus_file_sd_hosts }}"
  delegate_to: "{{ item }}"
  become: true
