---
- name: Ensure alertmanager package
  ansible.builtin.include_role:
    name: damex.apt.apt_packages
  vars:
    apt_packages: # noqa: var-naming[no-role-prefix]
      - name: "{{ alertmanager_package_name }}"
        version: "{{ alertmanager_package_version }}"
        state: "{{ alertmanager_package_state }}"
