---
- name: Ensure systemd service
  ansible.builtin.include_role:
    name: damex.systemd.systemd_service
  vars:
    systemd_service_name: "{{ alertmanager_service_name }}"
    systemd_service_restart_on: "{{ alertmanager_configuration_state.changed }}"
