---
- name: Ensure prometheus.yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_configuration_file }}"
    owner: root
    group: root
    mode: "0644"
    validate: /usr/bin/promtool check config %s
  become: true
  register: prometheus_configuration_state
